name: Deploy Nginx

on:
  push:
    branches:
    - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      
      IMAGE_TAG: ${{ github.sha }}
    steps:

    - name: code checkout
      uses: actions/checkout@v2
    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker europe-west4-docker.pkg.dev
        docker pull node:14-alpine
        docker build -t europe-west4-docker.pkg.dev/rational-symbol-431015-u0/docker-images/smp_front_image:$IMAGE_TAG .
        docker push europe-west4-docker.pkg.dev/rational-symbol-431015-u0/docker-images/smp_front_image:$IMAGE_TAG
      working-directory: SocialMediaPlatformFront
    - name: Deploy to GKE
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        IMG_TAG: ${{ github.sha }}
      run: |
        gcloud container clusters get-credentials frontend --region europe-west4-a
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        sed -i "s/IMAGE_TAG/$IMG_TAG/g" resources.yaml
        kubectl apply -f resources.yaml